### ISSUE TITLE
CMAKE_OSX_DEPLOYMENT_TARGET setting is affecting targets outside of SFML

### ISSUE THREAD

**Issue by ssrobins** [SFML/SFML#1436]
I build SFML by extracting the source into the CMake binary folder and use the CMake add_subdirectory command to add the targets to my build system.  That way, all I need to do to upgrade is change the version I'm targeting.

After upgrading from SFML 2.4.2 to 2.5.0, I oddly started getting build errors in Google Test like this for Mac OS X:

gtest-internal.h:894:44: error: no member named 'declval' in
      namespace 'std'
          class Iterator = decltype(::std::declval<const C&>().begin()),

I'm using the CMake Makefile generator and then running 'make' to build.

I traced it down to SFML setting CMAKE_OSX_DEPLOYMENT_TARGET to 10.7 if it didn't exist.

I was able to work around the error by passing -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 in my CMake command.

I don't think any library should be imposing settings on any other library, especially when they aren't dependent on each other.

I'm not highly experienced on OS X version targeting, but here's what I've noticed so far:

Up until this point, my variable CMAKE_OSX_DEPLOYMENT_TARGET had been blank.  Recently when I built a program on OS X 10.13.4 and tried to run it on OS X 10.11.6, it said I needed 10.13 or higher so I think the default target is the current OS X version.

According to this:
https://stackoverflow.com/questions/34208360/cmake-seems-to-ignore-cmake-osx-deployment-target
The variable has to be cached to work, which is unfortunate because that'll propagate it to the rest of the build system.

The CMake docs claim that it's initialized by MACOSX_DEPLOYMENT_TARGET environment variable, but mine was blank and I don't see that environment variable so I don't think it's present in a default config.
https://cmake.org/cmake/help/v3.0/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html

The CMAKE_OSX_SYSROOT on my machine looks like this:
CMAKE_OSX_SYSROOT:PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk

How about this instead:
Don't set CMAKE_OSX_DEPLOYMENT_TARGET at all

If CMAKE_OSX_DEPLOYMENT_TARGET is not set, grab the version from CMAKE_OSX_SYSROOT

Make sure the value derived from the above logic is >= 10.7.

**Comment by mantognini** [comment]
> How about this instead:
> Don't set CMAKE_OSX_DEPLOYMENT_TARGET at all
> If CMAKE_OSX_DEPLOYMENT_TARGET is not set, grab the version from CMAKE_OSX_SYSROOT
> Make sure the value derived from the above logic is >= 10.7.

If it fixes the issue, why not. Unless @Ceylo sees something else/better?

**Comment by Ceylo** [comment]
Before answering the CMake part I think it’s important to understand the first issue: why does gtest compilation fails when the deployment target is < 10.9 ?

And if they require the deployment target to be >= 10.9, why doesn’t gtest’s CMake code enforce this ?

**Comment by ssrobins** [comment]
gtest doesn't seem to be explicitly testing for deployment target, the
build failures communicate compatibility instead.  I think it's less about
deployment target and more about absence of language features in the older
version.

If CMAKE_OSX_DEPLOYMENT_TARGET is cached and forced like it is in SFML,
it's a global setting for the whole build system.  I'm not even sure if
gtest could enforce a different setting without affecting SFML's setting
too.  That's why target-based settings in CMake are heavily favored.  I'm
just not sure if this setting can be set by target.  Maybe directly set
the -mmacosx-version-min flag instead?

-Steve

**Comment by Ceylo** [comment]
Maybe I wasn't clear but the question is why wouldn't gtest's code compile with macOS 10.7 as min deployment target? The error you quote is about std::declval, which comes with C++11 which is supported since macOS 10.7, so it should just work. Why doesn't it?

Actually searching a bit I found this: https://stackoverflow.com/a/19819591/869385
So gtest code could work if it was explicitly setting its C++ standard version and standard library.

Yes CMAKE_OSX_DEPLOYMENT_TARGET is a global setting, but CMake doesn't provide any non-global setting for this at the moment. Using the compiler flag could work but would be non-portable because it's a different flag when building for iOS. So SFML would need to support both. Doing this is a bit like trying to fix CMake flaws ourselves, a bugfix in CMake repo would be much better. On the other side it's probably a good thing for this setting to be global: you most likely want all the targets in your project to be compiled with similar flags, otherwise you could end up making an executable that can run on 10.11 while the library it depends on requires 10.13 for example.

For the behavior described in the Stackoverflow link, I don't think it's a good idea to NOT set the deployment target: this leads to different behavior depending on where SFML is built (locally produced builds will require the latest OS with the behaviors that come with it, while SFML CI will require only 10.7 after updating its build command line).

All in all I don't have the feeling that we have a fix that is worth its drawbacks at the moment.

**Comment by ssrobins** [comment]
I'm not sure why the gtest build doesn't work with the 10.7 setting.  Does
it matter?  The point here is a change in SFML builds is affecting
libraries that has nothing to do with it.  It would be nice if CMake had a
target-based option or at least set OSX_DEPLOYMENT_TARGET to the current OS
X version by default.  I can provide that feedback to CMake.  However, even
if it got in the same release, it's doubtful you'd want to require the
latest CMake to build SFML so it'll take awhile before it can be used by
everyone.

Yes, I agree that the OSX_DEPLOYMENT_TARGET should be applied globally to a
project so all my executables and libraries are targeting the same
version.  That's why I set it globally in the main CMakeLists.txt file for
my project, along with CMAKE_CXX_STANDARD and many compiler/linker flags
I'd like to use everywhere.  I don't think it's the type of thing a library
should be setting for my whole project.

How about this:  Check for OSX_DEPLOYMENT_TARGET.  If it's not set, set the
cached variable to blank, fail the config step, and tell the user they must
set the variable to 10.7 or higher and that it will apply to all the user's
targets.  They can just add the value in the CMake GUI and re-configure.
SFML's CI system can pass -DOSX_DEPLOYMENT_TARGET=10.7 in the cmake command
to automatically have the proper value.  This way the user knows what's
being set and that it's global.  Downside is that there will be an initial
config failure when this variable isn't set.

If that doesn't work, I'm out of ideas.  I'm not blocked since I now set
OSX_DEPLOYMENT_TARGET so I defer to the judgement of the team.

-Steve

**Comment by Ceylo** [comment]
> I'm not sure why the gtest build doesn't work with the 10.7 setting.  Does
> it matter?

 It does! If you have requirements, you should set them.

> The point here is a change in SFML builds is affecting libraries that has nothing to do with it.

SFML kindly checks that no other entity did set a requirement. Nobody else has a requirement? Then SFML sets its own. That sounds pretty reasonable.

> However, even if it got in the same release, it's doubtful you'd want to require the latest CMake to build SFML so it'll take awhile before it can be used by everyone.

Right.

> I don't think it's the type of thing a library should be setting for my whole project.

I agree, but we don't have nice solution for now.

> This way the user knows what's being set and that it's global. Downside is that there will be an initial config failure when this variable isn't set.

You're trying to make SFML easier to use as a subproject, but on the other side it makes is more complicated to use as a standalone project. And from what I know it's mostly used standalone so I'm not convinced it's a good solution.

> If that doesn't work, I'm out of ideas.

I don't have other ideas as well… I'm not trying to kill all your ideas, but honestly none (including those I thought of) look satisfying at the moment. Really the best and easiest I can think of at the moment is for gtest to properly set its requirements.

**Comment by eXpl0it3r** [comment]
Am I understanding this correctly that you can currently set OSX_DEPLOYMENT_TARGET manually with the first cmake command to a value that will work for both SFML and Google Test?

Have you contacted Google Test and checked whether they think it might be a good idea to set OSX_DEPLOYMENT_TARGET if they expect a certain value anyways?

**Comment by ssrobins** [comment]
Here are all the cross-platform libraries I currently use:
Box2D, freetype, googletest, libpng, SDL2, SDL2_image, SDL2_mixer,
SDL2_ttf, SFML, and zlib

SFML is the only one that sets OSX_DEPLOYMENT_TARGET to a value.  Box2D
sets it to blank in a subdirectory CMake file that the main project may not
use, I'm not sure.

I'm not going to go around to other libraries that have, in my opinion,
correctly chosen to keep it unset and get them to set it just because you
are setting it.  That's not how build targets stay modular.  All of these
libraries work great as subdirectories in a CMake project except SFML.

I guess we'll have to agree to disagree.

**Comment by eXpl0it3r** [comment]
You didn't answer my first question.

**Comment by ssrobins** [comment]
Yes, I set OSX_DEPLOYMENT_TARGET to 10.9 in my main CMakeLists.txt file,
which works for both googletest and SFML.

**Comment by JonnyPtn** [comment]
I'm on the fence for this one.

Firstly, looking at the CMake docs for `CMAKE_OSX_DEPLOYMENT_TARGET` [here](https://cmake.org/cmake/help/v3.0/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html):
"It is intended to be set locally by the user creating a build tree" makes me think we shouldn't be setting it in the CMakeLists.txt

Secondly, I can't find the details on why SFML requires >10.7. If we didn't enforce this before SFML 2.5.0 then what's changed? What negative effect would not enforcing this have?

Although the percentage of people who use SFML as a subdirectory may be small, I'd wager the percentage of SFML users on 10.7 or lower is even smaller (Can't really find stats for this...)

If I had to choose, I'd say we should remove this setting, unless it has an adverse effect on other users (which as far as I can tell, it doesn't)

**Comment by eXpl0it3r** [comment]
Okay, let's remove it.

Anyone up for providing a PR?

**Comment by JonnyPtn** [comment]
Great, I'll put one together shortly

**Comment by JonnyPtn** [comment]
@ssrobins can you test #1467 if you get a chance please?

**Comment by ssrobins** [comment]
Sure, I'll spend some time this weekend.

**Comment by eXpl0it3r** [comment]
Fixed in e3c65090ea8ecd8a54e85ded8d9a50a315c13d15
