### PR TITLE
Fix compile on linux with gcc 12.2.0

### PR DESCRIPTION
**Pull request by oomek**
* [ ] Has this change been discussed on [the forum](https://en.sfml-dev.org/forums/index.php#c3) or in an issue before?
* [x] Does the code follow the SFML [Code Style Guide](https://www.sfml-dev.org/style.php)?
* [ ] Have you provided some example/test code for your changes?
* [ ] If you have additional steps which need to be performed list them as tasks!

----

## Description

Undefined NULL causes the following error when compiled on linux with gcc 12.2.0

```
/mnt/d/documents/gitkraken/sfml/src/SFML/Window/Vulkan.cpp: In static member function 'static void (* sf::Vulkan::getFunction(const char*))()':
/mnt/d/documents/gitkraken/sfml/src/SFML/Window/Vulkan.cpp:79:12: error: 'NULL' was not declared in this scope
   79 |     return NULL;
      |            ^~~~
/mnt/d/documents/gitkraken/sfml/src/SFML/Window/Vulkan.cpp:29:1: note: 'NULL' is defined in header '<cstddef>'; did you forget to '#include <cstddef>'?
   28 | #include <SFML/Window/Vulkan.hpp>
  +++ |+#include <cstddef>
   29 |
make[2]: *** [src/SFML/Window/CMakeFiles/sfml-window.dir/build.make:258: src/SFML/Window/CMakeFiles/sfml-window.dir/Vulkan.cpp.o] Error 1
```

This PR is related to the issue #

## Tasks

* [x] Tested on Linux
* [ ] Tested on Windows
* [ ] Tested on macOS
* [ ] Tested on iOS
* [ ] Tested on Android

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
SFMLBuildMaster: Build this please.

**Comment by eXpl0it3r** [comment]
SFMLBuildMaster: Build this please.

**Comment by oomek** [comment]
Is it me, or buildmaster has some issues?

**Comment by eXpl0it3r** [comment]
Yeah seems just flaky, I restarted it

**Review by eXpl0it3r — APPROVED** [review]

**Review by Bambo-Borris — APPROVED** [review]

**Review by JonnyPtn — APPROVED** [review]

**Comment by eXpl0it3r** [comment]
Thanks for the fix! 🙂
