### ISSUE TITLE
WindowBase::handleEvents() causes C4789 / Stack corruption in VS2022

### ISSUE THREAD

**Issue by n67-exe** [SFML/SFML#3454]
### Prerequisite Checklist

- [x] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [x] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [x] I am here to report an issue and not to just ask a question or look for help (use the [forum](https://en.sfml-dev.org/forums/index.php#c3) or [Discord](https://discord.gg/nr4X7Fh) instead)

## The problem
Calling WindowBase::handleEvents(...) with lambdas causes a compiler error in Visual Studio 2022:
```
...\WindowBase.inl(69,1): error C4789: in function "void WindowBase::handleEvents<... ::<lambda_1> const &>(... ::<lambda_1> const &)" buffer "overloadSet" of size 8 bytes will be overrun; 4 bytes will be written starting at offset 5
```
## Investigation
I tried forcing the compiler to ignore the error using `#pragma warning(disable : 4789)`. 
In Debug builds the program compiles, however when i run it a "Debug Error!" message box pops up with the text:
``Run-Time Check Failure #2 - Stack around the variable 'overloadSet' was corrupted.``
In the debugger the same error can be seen, marked as an exception originating from the line 73 of [WindowBase.inl](https://github.com/SFML/SFML/blob/44339c3d6766f63b9563955ab4cbe33465fc8542/include/SFML/Window/WindowBase.inl):
```cpp
}
```
Release builds seem to compile and run fine.

Inspecting the commit history i [found](https://github.com/SFML/SFML/commit/44339c3d6766f63b9563955ab4cbe33465fc8542) that this piece of code inside ``struct OverloadSet`` was added to prevent "stack corruption on MSVC":
```cpp
#if defined(_MSC_VER) && !defined(__clang__)
    unsigned char dummy; // Dummy variable to ensure that this struct is not empty thus avoiding a crash due to an MSVC bug
#endif
```
## Solution
I was able to compile and run the program without issues after commenting out the dummy variable on line 43 in [WindowBase.inl](https://github.com/SFML/SFML/blob/44339c3d6766f63b9563955ab4cbe33465fc8542/include/SFML/Window/WindowBase.inl):
```cpp
//unsigned char dummy; // Dummy variable to ensure that this struct is not empty thus avoiding a crash due to an MSVC bug
```
Maybe the fix was for the bug in older versions of MSVC that was fixed since then?
## Additional information
Full compiler error message:
```
...\SFML-3.0.0\include\SFML\Window\WindowBase.inl(69,1): error C4789: in function "void __thiscall sf::WindowBase::handleEvents<class `int __cdecl main(void)'::`2'::<lambda_1> const &>(class `int __cdecl main(void)'::`2'::<lambda_1> const &)" buffer "overloadSet" of size 8 bytes will be overrun; 4 bytes will be written starting at offset 5
```
Debug error message:
![Image](https://github.com/user-attachments/assets/13233853-aca8-4f74-a07e-8b75cd976b0b)

I used statically linked SFML 3.0.0 (32 bit) building for x86 on Windows 11.
I encountered this bug while using Visual Studio 2022 (x64) 17.13.2 (latest stable version) but the issue was present a few versions earlier as well (17.10 i think). 

### Your Environment

- OS / distro / window manager: Windows 11
- SFML version: 3.0.0 (32 bit)
- Compiler / toolchain: Visual Studio 2022 (x64) 17.13.2
- Special compiler / CMake flags: just plain "Console application" template with statically linked SFML

### Steps to reproduce

1. Compile the program in VS 2022 (slightly modified example from a [getting started tutorial](https://www.sfml-dev.org/tutorials/3.0/getting-started/visual-studio/))
2. Uncomment the first line to disable the error C4789 and run the program.

```cpp
//#pragma warning(disable : 4789)
#include <SFML/Graphics.hpp>

int main()
{
	sf::RenderWindow window(sf::VideoMode({ 200, 200 }), "SFML works!");
	sf::CircleShape shape(100.f);
	shape.setFillColor(sf::Color::Green);
	window.setFramerateLimit(60);

	const auto onClosed = [&](const sf::Event::Closed&)
		{
			window.close();
		};

	while (window.isOpen())
	{
		window.handleEvents(onClosed);

		window.clear();
		window.draw(shape);
		window.display();
	}
}
```

### Expected behavior

The circle should be green

### Actual behavior

The program doesn't compile/crashes

**Comment by Bambo-Borris** [comment]
Pretty sure we've seen this before, @ZXShady do you recall this one?

**Comment by ZXShady** [comment]
> This is the PR adding the `dummy` workaround: https://github.com/SFML/SFML/pull/3172
> 
> Perhaps we can work around this by adding an #ifdef around the dummy char depending on MSVC version


I think it is an issue with 32 bit vs 64 bit.

maybe we can do `_WIN32` and `_WIN64` checks

**Comment by eXpl0it3r** [comment]
> maybe we can do `_WIN32` and `_WIN64` checks

Does ARM64 define _WIN64 as well?

**Comment by texus** [comment]
I seem to be able to reproduce this issue in both 32bit and 64bit in debug mode.

After playing around and trying some changes, the easiest change that seemed to fix the issue is to initialize the dummy variable:
```diff
-unsigned char dummy;
+unsigned char dummy = 0;
```

I only tested whether the code works with Visual Studio 17.13.2

**Comment by ZXShady** [comment]
> I seem to be able to reproduce this issue in both 32bit and 64bit in debug mode.
> 
> After playing around and trying some changes, the easiest change that seemed to fix the issue is to initialize the dummy variable:
> ```diff
> -unsigned char dummy;
> +unsigned char dummy = 0;
> ```
> 
> I only tested whether the code works with Visual Studio 17.13.2

Weird that explicitly initializing it fixes the issue, it should already be initialized from aggregate initialization.

**Comment by eXpl0it3r** [comment]
If texus' solution works with both, older and newer VS version, that would be preferred.

Anyone wants to make a PR?

**Comment by n67-exe** [comment]
> I seem to be able to reproduce this issue in both 32bit and 64bit in debug mode.
> 
> After playing around and trying some changes, the easiest change that seemed to fix the issue is to initialize the dummy variable:
> 
> -unsigned char dummy;
> +unsigned char dummy = 0;
> I only tested whether the code works with Visual Studio 17.13.2

Initializing the variable seems to work for me too

**Comment by ChrisThrasher** [comment]
@n67-exe, can you recreate this problem with `master`? PR https://github.com/SFML/SFML/pull/3399 made some big changes to this code and some people are reporting that it seems to have fixed this issue.

**Comment by ChrisThrasher** [comment]
I’m closing this issue because we believe to have fixed this error. If you can still recreate the error with the `master` branch then please reopen this.
