### ISSUE TITLE
sfml-network doesn't work on Linux

### ISSUE THREAD

**Issue by KraXarN** [SFML/SFML#1156]
Hello!

The following code:

```
sf::Http http("<website>");
sf::Http::Request request("<url>");
sf::Http::Response response = http.sendRequest(request);
sf::Http::Response::Status status = response.getStatus();
```

Doesn't compile with the following errors:

```
/usr/include/SFML/Network/Socket.hpp:53:10: error: expected identifier before ‘int’
     enum Status
          ^

/usr/include/SFML/Network/Socket.hpp:54:5: error: expected unqualified-id before ‘{’ token
     {
     ^

/usr/include/SFML/Network/Ftp.hpp:74:14: error: expected identifier before ‘int’
         enum Status
              ^

/usr/include/SFML/Network/Ftp.hpp:75:9: error: expected unqualified-id before ‘{’ token
         {
         ^

/usr/include/SFML/Network/Ftp.hpp:146:41: error: ‘InvalidResponse’ was not declared in this scope
         explicit Response(Status code = InvalidResponse, const std::string& message = "");
                                         ^~~~~~~~~~~~~~~

/usr/include/SFML/Network/IpAddress.hpp:184:28: error: expected unqualified-id before numeric constant
     static const IpAddress None;      ///< Value representing an empty/invalid address
                            ^

/usr/include/SFML/Network/Http.hpp:201:14: error: expected identifier before ‘int’
         enum Status
              ^

/usr/include/SFML/Network/Http.hpp:202:9: error: expected unqualified-id before ‘{’ token
         {
         ^
```

Same code works fine on Windows 7 and macOS 10.12.

**Comment by SirSharpest** [comment]
What version of SFML are you using, is it the same on all platforms? Have you built yourself or used a package manager?

**Comment by KraXarN** [comment]
I'm using SFML 2.4.0 on all platforms. I tried both building it myself and though a package manager, both with 2.4.0. I'm running Manjaro.

**Comment by mantognini** [comment]
You are more than welcome to discuss your issue on the forum first as we try to keep this issue tracker for confirmed issues only. The procedure to open a bug/feature request is explained in [the contribution guidelines](http://www.sfml-dev.org/contribute.php). Thanks.

In this specific case, I'm pretty sure it's an issue with your environment that caused this. When reporting such issue on the forum, make sure to provide a SSCCE.
