### PR TITLE
Bugfix: Use the mouse button constant instead of 0 to avoid a compiler error on OSX

### PR DESCRIPTION
**Pull request by CouleeApps**
Simple fix that prevents a compiler error from breaking the build in Xcode 7.0.1

### CODE REVIEW

**Comment by mantognini** [comment]
What error? Build fine here.

BTW, we have >> [contribution guideline](https://github.com/SFML/SFML/blob/master/CONTRIBUTING) <<.

**Comment by CouleeApps** [comment]
The call to CGEventCreateMouseEvent was passing 0 (int) instead of kCGMouseButtonLeft (CGMouseButton), and was failing to build on the 10.11 SDK, 64 Bit. No idea why your environment works and mine doesn't, but this is a single-line replacement that just swaps the 0 for the inferred constant.

Here was the build error if you're interested:

    error: no matching function for call to 'CGEventCreateMouseEvent'
    CGEventRef event = CGEventCreateMouseEvent(NULL,
                       ^~~~~~~~~~~~~~~~~~~~~~~
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGEvent.h:57:33: note: candidate function not viable: no known conversion from 'int' to 'CGMouseButton' for 4th argument
    CG_EXTERN CGEventRef __nullable CGEventCreateMouseEvent(

**Comment by minirop** [comment]
they may have changed the definition from to a string enum. [Qt had the same prob](https://bugreports.qt.io/browse/QTBUG-47641?focusedCommentId=288292&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-288292)

**Comment by Bromeon** [comment]
As also mentioned in your link, simply passing `kCGMouseButtonLeft` is a bad idea, because it's unclear why exactly the left mouse button was chosen. You should add a comment -- there was one there, why did you remove it?

**Comment by mantognini** [comment]
I looked into it; what's weird is that with Xcode 7.2, SDK 10.11 on 10.10, it works fine. But if I try to mimic the `CF_ENUM` macro that is used to define `CGMouseButton` in some scrap project, I get an error too. Somewhere in there something fishy is happening...

Anyway, the Qt's bug report mentioned by @minirop sheds some light on the matter. The only thing missing in this PR is the comment referred by @Bromeon. Although, I would suggest replacing the incriminated line by `/* we don't care about this: */ CGMouseButton(0));` to make it even clearer.

**Comment by Bromeon** [comment]
> Although, I would suggest replacing the incriminated line by  /* we don't care about this: */ CGMouseButton(0));  to make it even clearer.

I wouldn't do this because 0 need not necessarily refer to a valid enumerator, and the function may not handle such values correctly. If it does now, it may still change in the future...

**Comment by mantognini** [comment]
Even though the doc specifically says this parameter is ignored in this context, on second thought you're right.

**Comment by CouleeApps** [comment]
kCGMouseButtonLeft is available in OS X 10.4 and later. I added the comment back (for documentation), but this should be compatible unless you plan on supporting OS X 10.3

**Comment by mantognini** [comment]
The constant is assured to be there, but its value *might* (however unlikely) be changed in later version.

Anyway, the PR is good for merging I'd say. :-)

**Comment by Bromeon** [comment]
I'd squash the two commits and write a better commit message than "Use the constant here..." and "...this variable..." :stuck_out_tongue:

**Comment by CouleeApps** [comment]
Alright, should be one commit now, and the title is more specific.

**Comment by Bromeon** [comment]
:+1:

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Comment by eXpl0it3r** [comment]
Merged in fe9b9c0cc78375b6ea74d56682e7751997db5a6e
